### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by rjlev20** [INFO-526-F24/project-01-Vizcats#2]
The following is the peer review of the project proposal by MintMindForDataViz The team members that participated in this review are 

- [Rafi Leviton] - @[rjlev20]
- [Arjun Kumar] - @[Arjun1-07]

- Describe the goal of the project.

The goal of the project is to answer environmental questions related to crop production. Specifically, the project will look into how the global production of staple crops has changed over time. 

- Describe the data used or collected.

The dataset they are working with is the FAOSTAT Crop and Livestock Production data. It provides global statistics on agricultural production, mainly crops and livestock. It tracks production volumes, harvested areas, and yields for various commodities. The data comes from over 200 countries.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

They will answer the research question by comparing the agricultural output of different regions to identify which areas produce the most food globally. They will also analyze changes in crop yields and production volumes over time and explore relationships between harvested areas and yields to assess agricultural efficiency.

- Is there anything that is unclear from the proposal?

It is unclear what specific visualizations will be made.

- Provide constructive feedback on how the team might be able to improve their project.

It could be helpful to clearly state what visualizations will be used to answer each question. 

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

We would be interested in seeing which crops production volume has grown the most over time. We would also be interested in seeing which regions of the world produce which crops. 

- Provide constructive feedback on any issues with file and/or code organization.

We are able to understand almost everything you have explained, but we would like you to mention what kind of approaches you will use to solve the research question, like creating a line plot to display a specifics crop production (corn in north america) over time.

- (Optional) Any further comments or feedback?

Great job, looking forward to the presentation.

**Comment by jayast29** [comment]
Thanks for the feedback
